[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_FLAGS = "--version"

# Environment variables
[build.environment]
  VITE_API_URL = "https://your-backend-url.herokuapp.com"

# Redirect all API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
